@startuml calc_steps

abstract ICalcStep {
    currentVal: 今の値
    prevVal: 前の値
    operation: 演算子
    ---
    actionDigit
    actionDot
    actionZeroZero
    actionPm
    actionAc
    actionC
    actionOperation
    actionEq
}

class FirstInputStep {
    currentVal: 今の値
    prevVal: 前の値
    operation: 演算子
    ---
    actionDigit
    actionDot
    actionZeroZero
    actionPm
    actionAc
    actionC
    actionOperation
    actionEq
}

class OperationSelectedStep {
    currentVal: 今の値
    prevVal: 前の値
    operation: 演算子
    ---
    actionDigit
    actionDot
    actionZeroZero
    actionPm
    actionAc
    actionC
    actionOperation
    actionEq
}

class SecondInputStep {
    currentVal: 今の値
    prevVal: 前の値
    operation: 演算子
    ---
    actionDigit
    actionDot
    actionZeroZero
    actionPm
    actionAc
    actionC
    actionOperation
    actionEq
}

class ResultStep {
    currentVal: 今の値
    prevVal: 前の値
    operation: 演算子
    ---
    actionDigit
    actionDot
    actionZeroZero
    actionPm
    actionAc
    actionC
    actionOperation
    actionEq
}

FirstInputStep -up-|> ICalcStep
OperationSelectedStep -up-|> ICalcStep
SecondInputStep -up-|> ICalcStep
ResultStep -up-|> ICalcStep

@enduml
