@startuml opkey_state

!include steps.pu

FirstInputStep -right-> OperationSelectedStep
OperationSelectedStep -> OperationSelectedStep
OperationSelectedStep -right[hidden]-> SecondInputStep
SecondInputStep -left-> OperationSelectedStep
SecondInputStep -right[hidden]-> ResultStep
ResultStep -left-> OperationSelectedStep

@enduml